version: '3.4'

services:
  web:
    restart: always
    build: .
    ports:
      - "8080:80"

  backend:
    restart: always
    build:
      context: .
      dockerfile: Backend.Dockerfile
    ports:
      - "5000:5000"
    environment:
      - NODE_ENV=production
    env_file:
        - .env

