version: '3.4'
#
#services:
#  web:
#    build: .
#    ports:
#      - "8080:80"
#  backend:
#    build:
#      context: .
#      target: backend
#    ports:
#      - "5000:5000"
#    environment:
#      - NODE_ENV=production
#    env_file:
#      - .env

#version: '3'

services:
  web:
    build: .
    ports:
      - "8080:80"

  backend:
    build:
      context: .
      dockerfile: Backend.Dockerfile
    ports:
      - "5000:5000"
    environment:
      - NODE_ENV=production
    env_file:
        - .env

